#!/usr/bin/env python3
"""
srt_translate.py — Translate a .srt subtitle file with Gemini or GPT.

Usage:
    python srt_translate.py input_ar.srt
    python srt_translate.py input_ar.srt -o output_id.srt --lang Indonesian
    python srt_translate.py input_ar.srt --provider openai --model gpt-4o

API keys (env vars, or pass --api-key):
    GEMINI_API_KEY   (or GOOGLE_API_KEY)   — for --provider gemini (default)
    OPENAI_API_KEY                         — for --provider openai

Install:
    pip install google-generativeai   # for Gemini
    pip install openai                # for GPT

How To Use?
    python srt_translate.py Teer_Enta_ar.srt
    # → writes Teer_Enta_ar_indonesian.srt (default target = Indonesian)

    # custom output name / language:
    python srt_translate.py movie_ar.srt -o movie_id.srt --lang Indonesian

    # use Gimini:
    export GEMINI_API_KEY=your_key_here
    python srt_translate.py --list-models
    python srt_translate.py movie_ar.srt --provider gemini --model gemini-flash-latest --batch-size 1000
 
   # use GPT instead:
    export OPENAI_API_KEY=your_key_here
    python srt_translate.py --list-models
    python srt_translate.py movie_ar.srt --provider openai --model gpt-4o

How it works:
    1. Parses the .srt into blocks (number, timestamp, text) — timestamps and
       numbering are NEVER sent to the model and NEVER regenerated by it; they
       are copied verbatim from the source file into the output.
    2. Sends the Arabic text in batches (default 100 lines/call) as JSON,
       with instructions to translate naturally, adapt jokes/idioms, localize
       religious expressions, keep profanity strength, and infer meaning
       through obvious ASR transcription errors.
    3. Because auto-generated captions often split one spoken sentence across
       several consecutive numbered lines, the model is instructed to
       translate the full sentence naturally and then distribute it back
       across the same line numbers — never merging or splitting entries —
       so the returned line count always matches what was sent.
    4. Progress is cached to "<output>.progress.json" so an interrupted run
       can resume without re-spending API calls.
"""

import argparse
import json
import os
import re
import sys
import time

# --------------------------------------------------------------------------
# SRT parsing / writing
# --------------------------------------------------------------------------

def parse_srt(path):
    with open(path, encoding="utf-8-sig") as f:
        content = f.read()
    blocks = []
    for raw in re.split(r"\n\s*\n", content.strip()):
        lines = raw.strip().split("\n")
        if len(lines) < 2:
            continue
        num = int(lines[0].strip())
        ts = lines[1].strip()
        text = "\n".join(lines[2:]).strip()
        blocks.append({"num": num, "ts": ts, "text": text})
    blocks.sort(key=lambda b: b["num"])
    return blocks


def write_srt(blocks, translations, output_path):
    out = []
    for b in blocks:
        text = translations.get(b["num"], b["text"])
        out.append(str(b["num"]))
        out.append(b["ts"])
        out.append(text.strip())
        out.append("")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")


# --------------------------------------------------------------------------
# Prompt
# --------------------------------------------------------------------------

SYSTEM_PROMPT_TEMPLATE = """You are a professional subtitle translator specializing in natural, \
colloquial movie subtitle translation.

Source language: {source_lang}. This is an auto-generated (speech-recognition) subtitle \
file, so it may contain transcription errors, misheard words, or garbled phrases — infer \
the most likely intended meaning from context and translate that.

Target language: {target_lang}, written in a natural, everyday SPOKEN/colloquial register \
— not formal or literary.

Translation rules:
- Prioritize natural meaning and dialogue flow over literal, word-for-word translation.
- Adapt idioms, slang, and cultural references into equivalent natural expressions in \
{target_lang}, even when the literal wording is completely different.
- Rewrite jokes and wordplay so they land with a {target_lang}-speaking audience, rather \
than translating them literally.
- Preserve the emotional tone, personality, and register of each speaker (angry stays \
angry, sarcastic stays sarcastic, tender stays tender).
- Translate religious/devotional expressions (e.g. "Wallahi", "Insha'Allah", \
"Astaghfirullah") into natural {target_lang} equivalents rather than leaving them \
untranslated or transliterated.
- Keep insults and profanity at the same intensity using common natural {target_lang} \
equivalents — do not soften or censor them.
- Bracketed production tags like [MUSIC], [APPLAUSE], [LAUGHTER] should be translated to \
the equivalent bracketed tag in {target_lang} (e.g. "[Musik]").

CRITICAL formatting constraint:
You will receive a JSON array of {{"n": <line number>, "text": <source line>}} objects. A \
single spoken sentence is often split mid-word or mid-clause across several consecutive \
line numbers (that's how the auto-captioning broke it up).
- You MUST return exactly one translated entry per input line number.
- NEVER merge two input line numbers into one output entry.
- NEVER split one input line number's content across two output entries.
- When consecutive lines form one sentence, translate the sentence naturally as a whole, \
then distribute that natural translation back across those same line numbers in order, so \
reading the output entries in sequence produces one coherent sentence.
- Every single input line number must appear exactly once in your output — do not skip \
any, do not invent extra ones.

Return ONLY valid JSON (no markdown code fences, no commentary) in exactly this shape:
{{"translations": [{{"n": <line number as integer>, "text": "<translated text>"}}, ...]}}
"""


def build_batch_payload(batch):
    return json.dumps(
        [{"n": b["num"], "text": b["text"]} for b in batch],
        ensure_ascii=False,
    )


# --------------------------------------------------------------------------
# Provider calls
# --------------------------------------------------------------------------

def call_gemini(system_prompt, user_payload, model, api_key):
    import google.generativeai as genai

    genai.configure(api_key=api_key)
    gmodel = genai.GenerativeModel(model_name=model, system_instruction=system_prompt)
    response = gmodel.generate_content(
        user_payload,
        generation_config={"response_mime_type": "application/json"},
    )
    return response.text


def call_openai(system_prompt, user_payload, model, api_key):
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_payload},
        ],
        response_format={"type": "json_object"},
    )
    return response.choices[0].message.content


class ModelNotFoundError(RuntimeError):
    pass


class QuotaExceededError(RuntimeError):
    pass


# Google's 429 error text embeds the server-suggested wait, e.g.
# "... retry_delay { seconds: 34 } ...". Respecting it (instead of a short
# fixed backoff) is the difference between actually recovering and just
# burning through max_retries on a guaranteed-repeat failure.
_RETRY_DELAY_RE = re.compile(r"retry_delay\s*\{\s*seconds:\s*(\d+)")


def _is_quota_error(err_text):
    return "429" in err_text and ("quota" in err_text.lower() or "rate" in err_text.lower())


# Tracks the last call time per-process so --rpm can throttle *before* hitting
# a 429, not just react after one.
_last_call_at = [0.0]


def _throttle(min_interval):
    if min_interval <= 0:
        return
    elapsed = time.time() - _last_call_at[0]
    if elapsed < min_interval:
        time.sleep(min_interval - elapsed)
    _last_call_at[0] = time.time()


def call_provider(provider, model, api_key, system_prompt, user_payload, max_retries,
                   min_interval=0.0):
    last_err = None
    for attempt in range(1, max_retries + 1):
        _throttle(min_interval)
        try:
            if provider == "gemini":
                return call_gemini(system_prompt, user_payload, model, api_key)
            elif provider == "openai":
                return call_openai(system_prompt, user_payload, model, api_key)
            else:
                raise ValueError(f"Unknown provider: {provider}")
        except Exception as e:  # noqa: BLE001 - want to retry on any transient error
            err_text = str(e)

            # A missing/deprecated model won't fix itself on retry — fail fast
            # instead of burning rounds of backoff on a guaranteed-repeat 404.
            if "404" in err_text and "model" in err_text.lower():
                raise ModelNotFoundError(
                    f"Model '{model}' is not available: {e}\n"
                    f"Run with --list-models to see what your API key can use."
                ) from e

            if _is_quota_error(err_text):
                m = _RETRY_DELAY_RE.search(err_text)
                if m:
                    wait = int(m.group(1)) + 2  # small buffer past the server's suggestion
                elif attempt == max_retries:
                    # No suggested delay and out of retries — this is a quota/billing
                    # ceiling (daily cap, free-tier RPM/RPD limit, etc.), not something
                    # a longer local backoff can push through. Surface it clearly.
                    raise QuotaExceededError(
                        f"Gemini quota/rate limit exceeded: {e}\n"
                        f"Fixes: wait for the quota window to reset, enable billing / "
                        f"upgrade your plan at https://ai.dev/rate-limit, lower request "
                        f"volume with --rpm (e.g. --rpm 10), or raise --batch-size so "
                        f"fewer requests are needed for the same file."
                    ) from e
                else:
                    wait = min(30 * attempt, 120)
                print(f"  [warn] Quota/rate limit hit (attempt {attempt}/{max_retries}) "
                      f"— waiting {wait}s before retry", file=sys.stderr)
                time.sleep(wait)
                continue

            last_err = e
            wait = min(2 ** attempt, 30)
            print(f"  [warn] API call failed (attempt {attempt}/{max_retries}): {e} "
                  f"— retrying in {wait}s", file=sys.stderr)
            time.sleep(wait)
    raise RuntimeError(f"Provider call failed after {max_retries} attempts: {last_err}")


# --------------------------------------------------------------------------
# Response parsing / validation
# --------------------------------------------------------------------------

def parse_model_json(raw_text):
    text = raw_text.strip()
    # Strip markdown code fences if the model added them despite instructions.
    if text.startswith("```"):
        text = re.sub(r"^```(json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    data = json.loads(text)
    if isinstance(data, dict) and "translations" in data:
        items = data["translations"]
    elif isinstance(data, list):
        items = data
    else:
        raise ValueError(f"Unexpected JSON shape: {type(data)}")
    result = {}
    for item in items:
        result[int(item["n"])] = str(item["text"])
    return result


# --------------------------------------------------------------------------
# Batch translation with caching/resume
# --------------------------------------------------------------------------

def chunk(blocks, size):
    for i in range(0, len(blocks), size):
        yield blocks[i:i + size]


def translate_all(blocks, provider, model, api_key, source_lang, target_lang,
                   batch_size, max_retries, progress_path, min_interval=0.0):
    translations = {}
    if os.path.exists(progress_path):
        with open(progress_path, encoding="utf-8") as f:
            translations = {int(k): v for k, v in json.load(f).items()}
        print(f"Resuming from cache: {len(translations)} lines already translated.")

    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(
        source_lang=source_lang, target_lang=target_lang
    )

    remaining_blocks = [b for b in blocks if b["num"] not in translations]
    batches = list(chunk(remaining_blocks, batch_size))
    total_batches = len(batches)

    for i, batch in enumerate(batches, 1):
        nums = [b["num"] for b in batch]
        print(f"Batch {i}/{total_batches} (lines {nums[0]}-{nums[-1]}, {len(batch)} lines)...")

        payload = build_batch_payload(batch)
        raw = call_provider(provider, model, api_key, system_prompt, payload, max_retries,
                             min_interval)

        try:
            result = parse_model_json(raw)
        except Exception as e:
            print(f"  [error] Could not parse JSON response: {e}\nRaw response:\n{raw[:2000]}",
                  file=sys.stderr)
            result = {}

        missing = [n for n in nums if n not in result]
        if missing:
            print(f"  [warn] {len(missing)} lines missing from response "
                  f"(e.g. {missing[:5]}) — retrying just those lines individually.")
            for n in missing:
                b = next(x for x in batch if x["num"] == n)
                single_payload = build_batch_payload([b])
                try:
                    raw_single = call_provider(provider, model, api_key, system_prompt,
                                                single_payload, max_retries, min_interval)
                    single_result = parse_model_json(raw_single)
                    result.update(single_result)
                except (QuotaExceededError, ModelNotFoundError):
                    # Not a per-line problem — don't mask it as a fallback-to-source
                    # for every remaining line, let it stop the run so progress
                    # (already cached) can be resumed once the real issue is fixed.
                    raise
                except Exception as e:
                    print(f"  [error] Line {n} failed even individually ({e}); "
                          f"keeping original source text.", file=sys.stderr)
                    result[n] = b["text"]

        translations.update(result)

        # Persist progress after every batch so interrupted runs can resume.
        with open(progress_path, "w", encoding="utf-8") as f:
            json.dump(translations, f, ensure_ascii=False, indent=1)

    return translations


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def default_model(provider):
    # "-latest" aliases track whatever Google currently recommends, so this
    # default won't go stale the way a pinned version (e.g. "gemini-2.5-flash")
    # eventually does when that version is retired for new API keys.
    return "gemini-flash-latest" if provider == "gemini" else "gpt-4o"


def list_gemini_models(api_key):
    import google.generativeai as genai

    genai.configure(api_key=api_key)
    print("Models available to this API key that support generateContent:\n")
    for m in genai.list_models():
        if "generateContent" in m.supported_generation_methods:
            print(f"  {m.name}")


def resolve_api_key(provider, cli_key):
    if cli_key:
        return cli_key
    if provider == "gemini":
        return os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    return os.environ.get("OPENAI_API_KEY")


def main():
    parser = argparse.ArgumentParser(description="Translate a .srt file with Gemini or GPT.")
    parser.add_argument("input_srt", nargs="?", help="Path to the source .srt file")
    parser.add_argument("--list-models", action="store_true",
                         help="List models your Gemini API key can use, then exit")
    parser.add_argument("-o", "--output", help="Output .srt path (default: <input>_<lang>.srt)")
    parser.add_argument("--lang", default="Indonesian",
                         help="Target language (default: Indonesian)")
    parser.add_argument("--source-lang", default="Egyptian Arabic (colloquial dialect)",
                         help="Description of the source language/dialect for the model")
    parser.add_argument("--provider", choices=["gemini", "openai"], default="gemini")
    parser.add_argument("--model", default=None,
                         help="Model name (default: gemini-2.5-flash / gpt-4o)")
    parser.add_argument("--api-key", default=None,
                         help="API key (else read from env var)")
    parser.add_argument("--batch-size", type=int, default=100,
                         help="Subtitle lines per API call (default: 100)")
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--rpm", type=float, default=0,
                         help="Throttle to at most this many API requests per minute "
                              "(0 = no throttle). Set this if you're hitting 429 quota "
                              "errors, e.g. --rpm 10 for a free-tier key.")
    parser.add_argument("--fresh", action="store_true",
                         help="Ignore any cached progress and start over")
    args = parser.parse_args()

    api_key = resolve_api_key(args.provider, args.api_key)
    if not api_key:
        env_hint = "GEMINI_API_KEY (or GOOGLE_API_KEY)" if args.provider == "gemini" else "OPENAI_API_KEY"
        sys.exit(f"No API key found. Set {env_hint} or pass --api-key.")

    if args.list_models:
        if args.provider != "gemini":
            sys.exit("--list-models currently only supports --provider gemini.")
        list_gemini_models(api_key)
        return

    if not args.input_srt:
        sys.exit("input_srt is required (unless using --list-models).")

    model = args.model or default_model(args.provider)

    if not args.output:
        base, ext = os.path.splitext(args.input_srt)
        lang_slug = re.sub(r"[^a-zA-Z0-9]+", "", args.lang).lower()
        args.output = f"{base}_{lang_slug}{ext}"

    progress_path = args.output + ".progress.json"
    if args.fresh and os.path.exists(progress_path):
        os.remove(progress_path)

    min_interval = 60.0 / args.rpm if args.rpm > 0 else 0.0

    print(f"Parsing {args.input_srt} ...")
    blocks = parse_srt(args.input_srt)
    print(f"Found {len(blocks)} subtitle blocks.")

    try:
        translations = translate_all(
            blocks=blocks,
            provider=args.provider,
            model=model,
            api_key=api_key,
            source_lang=args.source_lang,
            target_lang=args.lang,
            batch_size=args.batch_size,
            max_retries=args.max_retries,
            progress_path=progress_path,
            min_interval=min_interval,
        )
    except (ModelNotFoundError, QuotaExceededError) as e:
        print(f"\n[stopped] {e}", file=sys.stderr)
        print(f"Progress so far is cached in {progress_path} — rerun the same command "
              f"once resolved and it will resume from there.", file=sys.stderr)
        sys.exit(1)

    write_srt(blocks, translations, args.output)
    print(f"Done. Wrote {len(blocks)} blocks to {args.output}")

    missing = [b["num"] for b in blocks if b["num"] not in translations]
    if missing:
        print(f"[warn] {len(missing)} lines fell back to source text: {missing}")
    else:
        # Clean up the progress cache only on a fully successful run.
        if os.path.exists(progress_path):
            os.remove(progress_path)


if __name__ == "__main__":
    main()
